/**
 * @packageDocumentation
 * @module api.functional.api_key
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { CreateApiKeyDto } from "../../../../apps/backend/src/modules/api-key/dto/create-api-key.dto";
import type { RegenerateApiKeyDto } from "../../../../apps/backend/src/modules/api-key/dto/regenerate-api-key.dto";
import type {
  ApiKeyCreatedEntity,
  ApiKeyEntity,
} from "../../../../apps/backend/src/modules/api-key/entities/api-key.entity";

/**
 * @controller ApiKeyController.findAll
 * @path GET /api-key
 * @accessor api.functional.api_key.findAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
): Promise<findAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...findAll.METADATA,
    template: findAll.METADATA.path,
    path: findAll.path(),
  });
}
export namespace findAll {
  export type Output = Primitive<Array<ApiKeyEntity>>;

  export const METADATA = {
    method: "GET",
    path: "/api-key",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api-key";
}

/**
 * @controller ApiKeyController.create
 * @path POST /api-key
 * @accessor api.functional.api_key.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<CreateApiKeyDto>;
  export type Output = Primitive<ApiKeyCreatedEntity>;

  export const METADATA = {
    method: "POST",
    path: "/api-key",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api-key";
}

/**
 * @controller ApiKeyController.regenerate
 * @path PUT /api-key
 * @accessor api.functional.api_key.regenerate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function regenerate(
  connection: IConnection,
  body: regenerate.Body,
): Promise<regenerate.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...regenerate.METADATA,
      template: regenerate.METADATA.path,
      path: regenerate.path(),
    },
    body,
  );
}
export namespace regenerate {
  export type Body = Primitive<RegenerateApiKeyDto>;
  export type Output = Primitive<ApiKeyCreatedEntity>;

  export const METADATA = {
    method: "PUT",
    path: "/api-key",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api-key";
}

/**
 * @controller ApiKeyController.remove
 * @path DELETE /api-key/:id
 * @accessor api.functional.api_key.remove
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function remove(
  connection: IConnection,
  id: string,
): Promise<remove.Output> {
  return PlainFetcher.fetch(connection, {
    ...remove.METADATA,
    template: remove.METADATA.path,
    path: remove.path(id),
  });
}
export namespace remove {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: "DELETE",
    path: "/api-key/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/api-key/${encodeURIComponent(id?.toString() ?? "null")}`;
}
