"use client";

import {
  Book,
  Film,
  Home,
  Gamepad,
  List,
  Search,
  Tv,
  Tv2,
  Music,
  BookA,
  Compass,
  Calendar,
  User,
  Users,
  Trophy,
} from "lucide-react";

import type { NavbarConfig } from "@/types/NavbarConfig";
import { AquilaFlags, RunaFlags } from "@runa/permissions";
import { SidebarConfig } from "@/types/SidebarConfig";

type TranslateFn = (key: string, options?: Record<string, unknown>) => string;

export const getAquilaSidebarConfig = (
  session: any,
  userConnections: any[] = [],
  t: TranslateFn = (key) => key,
): SidebarConfig => [
  {
    section: "#$Phone",
    items: [
      {
        label: t("sidebarHome"),
        href: "/aquila",
        preventRedirect: false,
        icon: <Home className="h-4 w-4" />,
        subtitle: t("sidebarHomeSubtitle"),
        position: 1,
      },
      {
        label: t("sidebarBrowse"),
        href: "/aquila/browse",
        icon: <Search className="h-4 w-4" />,
        preventRedirect: false,
        subtitle: t("sidebarBrowse"),
        position: 2,
        children: [
          {
            label: t("sidebarSearch"),
            href: "/aquila/browse",
            preventRedirect: false,
            subtitle: t("sidebarSearch"),
            icon: <Search className="h-3.5 w-3.5" />,
          },
          {
            label: t("sidebarRankings"),
            href: "/aquila/rankings",
            preventRedirect: false,
            subtitle: t("sidebarRankings"),
            icon: <Trophy className="h-3.5 w-3.5" />,
          },
        ],
      },
      {
        label: t("sidebarCalendar"),
        href: "/aquila/calendar",
        icon: <Calendar className="h-4 w-4" />,
        preventRedirect: false,
        subtitle: t("sidebarCalendar"),
        position: 3,
      },
      {
        label: t("sidebarDiscover"),
        href: "/aquila/discover",
        icon: <Compass className="h-4 w-4" />,
        preventRedirect: false,
        subtitle: t("sidebarDiscover"),
        position: 4,
        children: [
          {
            label: t("sidebarAnime"),
            href: "/aquila/discover/anime",
            preventRedirect: false,
            subtitle: t("sidebarAnime"),
            icon: <Film className="h-3.5 w-3.5" />,
          },
          {
            label: t("sidebarManga"),
            href: "/aquila/discover/manga",
            preventRedirect: false,
            subtitle: t("sidebarManga"),
            icon: <Book className="h-3.5 w-3.5" />,
          },
          {
            label: t("sidebarMovies"),
            href: "/aquila/discover/movies",
            preventRedirect: false,
            subtitle: t("sidebarMovies"),
            icon: <Tv2 className="h-3.5 w-3.5" />,
          },
          {
            label: t("sidebarTvShows"),
            href: "/aquila/discover/tv",
            preventRedirect: false,
            subtitle: t("sidebarTvShows"),
            icon: <Tv className="h-3.5 w-3.5" />,
          },
          {
            label: t("sidebarGames"),
            href: "/aquila/discover/games",
            preventRedirect: false,
            subtitle: t("sidebarGames"),
            icon: <Gamepad className="h-3.5 w-3.5" />,
          },
          {
            label: t("sidebarBooks"),
            href: "/aquila/discover/books",
            preventRedirect: false,
            subtitle: t("sidebarBooks"),
            icon: <BookA className="h-3.5 w-3.5" />,
          },
          {
            label: t("sidebarCharacters"),
            href: "/aquila/discover/characters",
            preventRedirect: false,
            subtitle: t("sidebarCharacters"),
            icon: <User className="h-3.5 w-3.5" />,
          },
          {
            label: t("sidebarActors"),
            href: "/aquila/discover/actors",
            preventRedirect: false,
            subtitle: t("sidebarActors"),
            icon: <Users className="h-3.5 w-3.5" />,
          },
        ],
      },
    ],
  },
  {
    section: "",
    items: [
      {
        dataKey: "Home",
        label: t("sidebarHome"),
        href: "/aquila",
        icon: <Home className="h-4 w-4" />,
        preventRedirect: false,
        subtitle: t("sidebarHomeSubtitle"),
      },
      {
        dataKey: "Browse",
        label: t("sidebarBrowse"),
        href: "/aquila/browse",
        icon: <Search className="h-4 w-4" />,
        preventRedirect: false,
        subtitle: t("sidebarBrowse"),
        children: [
          {
            dataKey: "Rankings",
            label: t("sidebarRankings"),
            href: "/aquila/rankings",
            preventRedirect: false,
            subtitle: t("sidebarRankings"),
            icon: <Trophy className="h-3.5 w-3.5" />,
          },
        ],
      },
      {
        dataKey: "Calendar",
        label: t("sidebarCalendar"),
        href: "/aquila/calendar",
        icon: <Calendar className="h-4 w-4" />,
        preventRedirect: false,
        subtitle: t("sidebarCalendar"),
      },
      {
        dataKey: "Discover",
        label: t("sidebarDiscover"),
        href: "/aquila/discover",
        icon: <Compass className="h-4 w-4" />,
        preventRedirect: false,
        subtitle: t("sidebarDiscover"),
        children: [
          {
            dataKey: "Anime",
            label: t("sidebarAnime"),
            href: "/aquila/discover/anime",
            preventRedirect: false,
            subtitle: t("sidebarAnime"),
            icon: <Film className="h-3.5 w-3.5" />,
          },
          {
            dataKey: "Manga",
            label: t("sidebarManga"),
            href: "/aquila/discover/manga",
            preventRedirect: false,
            subtitle: t("sidebarManga"),
            icon: <Book className="h-3.5 w-3.5" />,
          },
          {
            dataKey: "Movies",
            label: t("sidebarMovies"),
            href: "/aquila/discover/movies",
            preventRedirect: false,
            subtitle: t("sidebarMovies"),
            icon: <Tv2 className="h-3.5 w-3.5" />,
          },
          {
            dataKey: "TvShows",
            label: t("sidebarTvShows"),
            href: "/aquila/discover/tv",
            preventRedirect: false,
            subtitle: t("sidebarTvShows"),
            icon: <Tv className="h-3.5 w-3.5" />,
          },
          {
            dataKey: "Games",
            label: t("sidebarGames"),
            href: "/aquila/discover/games",
            preventRedirect: false,
            subtitle: t("sidebarGames"),
            icon: <Gamepad className="h-3.5 w-3.5" />,
          },
          {
            dataKey: "Books",
            label: t("sidebarBooks"),
            href: "/aquila/discover/books",
            preventRedirect: false,
            subtitle: t("sidebarBooks"),
            icon: <BookA className="h-3.5 w-3.5" />,
          },
          {
            dataKey: "Characters",
            label: t("sidebarCharacters"),
            href: "/aquila/discover/characters",
            preventRedirect: false,
            subtitle: t("sidebarCharacters"),
            icon: <User className="h-3.5 w-3.5" />,
          },
          {
            dataKey: "Actors",
            label: t("sidebarActors"),
            href: "/aquila/discover/actors",
            preventRedirect: false,
            subtitle: t("sidebarActors"),
            icon: <Users className="h-3.5 w-3.5" />,
          },
        ],
      },
    ],
  },
  {
    section: t("sidebarLibrary"),
    dataKey: "Library",
    permissions: RunaFlags.LOGGED_IN,
    items: [
      {
        label: t("sidebarAnime"),
        href: `/aquila/user/${session?.user?.username}/anime`,
        icon: <Film className="h-4 w-4" />,
        preventRedirect: false,
        subtitle: t("sidebarAnime"),
      },
      {
        label: t("sidebarManga"),
        href: `/aquila/user/${session?.user?.username}/manga`,
        icon: <Book className="h-4 w-4" />,
        preventRedirect: false,
        subtitle: t("sidebarManga"),
      },
      {
        label: t("sidebarMovies"),
        href: `/aquila/user/${session?.user?.username}/movies`,
        icon: <Tv2 className="h-4 w-4" />,
        preventRedirect: false,
        subtitle: t("sidebarMovies"),
      },
      {
        label: t("sidebarTvShows"),
        href: `/aquila/user/${session?.user?.username}/tv`,
        icon: <Tv className="h-4 w-4" />,
        preventRedirect: false,
        subtitle: t("sidebarTvShows"),
      },
      {
        label: t("sidebarGames"),
        href: `/aquila/user/${session?.user?.username}/games`,
        icon: <Gamepad className="h-4 w-4" />,
        preventRedirect: false,
        subtitle: t("sidebarGames"),
      },
      {
        label: t("sidebarBooks"),
        href: `/aquila/user/${session?.user?.username}/books`,
        icon: <BookA className="h-4 w-4" />,
        preventRedirect: false,
        subtitle: t("sidebarBooks"),
      },
    ],
  },
  {
    section: t("sidebarConnections"),
    dataKey: "Connections",
    permissions: RunaFlags.LOGGED_IN,
    items: (userConnections || []).map(
      (connection: { provider: string; linkedUsername: string }) => {
        return {
          label: `${connection.provider} / ${connection.linkedUsername}`,
          href: `/aquila/user/${session?.user?.username}/connections/${connection.provider.toLowerCase()}`,
          preventRedirect: false,
          icon: <List className="h-4 w-4" />,
          subtitle: connection.provider,
          children: [
            {
              label: "Browse",
              subtitle: `Browse ${connection.provider}`,
              href: `/aquila/user/${session?.user?.username}/connections/${connection.provider.toLowerCase()}/browse`,
              icon: <Search className="h-4 w-4" />,
              preventRedirect: false,
            },
          ],
        };
      },
    ),
  },
];
