services:
  runa-frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEST_PORT=${NEST_PORT}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - NEXT_PUBLIC_SIMKL_CLIENT_ID=${SIMKL_CLIENT_ID}
    container_name: runa-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

  runa-backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: runa-backend
    user: "0:0"
    ports:
      - "${NEST_PORT}:${NEST_PORT}"
    environment:
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ~/app-data/runa/uploads:/app/uploads
    restart: unless-stopped

  runa-lynx:
    build:
      context: .
      dockerfile: apps/lynx-bot/Dockerfile
    container_name: runa-lynx-bot
    ports:
      - "${LYNX_PORT}:${LYNX_PORT}"
    restart: unless-stopped
