networks:
  Runerra:
    external: true


services:
  runa-frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEST_PORT=${NEST_PORT}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - NEXT_PUBLIC_SIMKL_CLIENT_ID=${SIMKL_CLIENT_ID}
    container_name: runa-frontend
    networks:
      Runerra:
        ipv4_address: 172.20.0.100
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NEST_API_URL=http://runa-backend:${NEST_PORT:-4000}
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000 # DevSkim: ignore DS137138, DS162092
      - LYNX_API_URL=http://lynx-bot:4444
      - TZ=Europe/Bratislava

    restart: unless-stopped

  runa-backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: runa-backend
    user: "0:0"
    networks:
      Runerra:
        ipv4_address: 172.20.0.101
    ports:
      - "${NEST_PORT}:${NEST_PORT}"
    env_file:
      - .env
    environment:
      - UPLOAD_DIR=/app/uploads
      - TZ=Europe/Bratislava
    volumes:
      - ~/app-data/runa/uploads:/app/uploads
    restart: unless-stopped

  runa-lynx:
    build:
      context: .
      dockerfile: apps/lynx-bot/Dockerfile
    container_name: runa-lynx-bot
    networks:
      Runerra:
        ipv4_address: 172.20.0.102
    ports:
      - "${LYNX_PORT}:${LYNX_PORT}"

    env_file:
      - .env
    environment:
      - TZ=Europe/Bratislava
    restart: unless-stopped
