/**
 * @packageDocumentation
 * @module api.functional.anime
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";

import type { SearchAnimeDto } from "../../../../apps/backend/src/modules/anime/dto/search-anime.dto";
import type { AnimeSearchEntity } from "../../../../apps/backend/src/modules/anime/entities/anime-search.entity";
import type { AnimeEntity } from "../../../../apps/backend/src/modules/anime/entities/anime.entity";

/**
 * @controller AnimeController.search
 * @path GET /anime/search
 * @accessor api.functional.anime.search
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function search(
  connection: IConnection,
  query: search.Query,
): Promise<search.Output> {
  return PlainFetcher.fetch(connection, {
    ...search.METADATA,
    template: search.METADATA.path,
    path: search.path(query),
  });
}
export namespace search {
  export type Query = Resolved<SearchAnimeDto>;
  export type Output = Primitive<AnimeSearchEntity>;

  export const METADATA = {
    method: "GET",
    path: "/anime/search",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/anime/search";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}

/**
 * @controller AnimeController.getAnime
 * @path GET /anime/:id
 * @accessor api.functional.anime.getAnime
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAnime(
  connection: IConnection,
  id: string,
): Promise<getAnime.Output> {
  return PlainFetcher.fetch(connection, {
    ...getAnime.METADATA,
    template: getAnime.METADATA.path,
    path: getAnime.path(id),
  });
}
export namespace getAnime {
  export type Output = Primitive<AnimeEntity>;

  export const METADATA = {
    method: "GET",
    path: "/anime/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/anime/${encodeURIComponent(id?.toString() ?? "null")}`;
}
