export const PERMISSION_DESCRIPTIONS: Record<string, string> = {
  ADMINISTRATOR: "Grants bypass access to all pages and permissions",
  POLARIS_VIEW: "Basic access to Polaris platform",
  POLARIS_MANAGE: "Administrative tools inside Polaris",
  POLARIS_LOGGED_IN: "Required flag to access user dashboard",
  LYNX_VIEW: "Access Lynx web interface",
  LYNX_MANAGE: "Full admin rights in Lynx bot",
  LYNX_LOGGED_IN: "General authenticated operations in Lynx",
  LYNX_MANAGE_DATABASE: "Inspect and modify databases",
  LYNX_GUILD_CHAT: "Interact in guild text channels",
  LYNX_DM_CHAT: "Send private messages via bot",
  LYNX_VIEW_LOGS: "Access system and bot console audit logs",
  LYNX_MANAGE_CONFIG: "Configure crons, commands and homework modules",
  AQUILA_VIEW: "Browse and view library catalogs",
  AQUILA_MANAGE: "Content administrative features",
  AQUILA_LOGGED_IN: "General user actions in Aquila library",
  AQUILA_EDIT_ANIME: "Create and modify anime database records",
  AQUILA_EDIT_MANGA: "Create and modify manga database records",
  AQUILA_EDIT_MOVIE: "Create and modify movie database records",
  AQUILA_EDIT_TV: "Create and modify TV show database records",
  AQUILA_EDIT_GAME: "Create and modify game database records",
  AQUILA_EDIT_BOOK: "Create and modify book database records",
  AQUILA_IMPORT_LIST: "Import lists from extensions like AniList, MyAnimeList, and Simkl",
};
