/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as user from "./user/index";
export * as auth from "./auth/index";
export * as anime from "./anime/index";
export * as manga from "./manga/index";
export * as movie from "./movie/index";
export * as tv from "./tv/index";
export * as api_key from "./api_key/index";
export * as connection from "./connection/index";
export * as test from "./test/index";
