/**
 * @packageDocumentation
 * @module api.functional.test.apikey
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { ApiKeyResponseEntity } from "../../../../../apps/backend/src/modules/test/entities/test-response.entity";

/**
 * @controller TestController.apiKey
 * @path GET /test/apikey
 * @accessor api.functional.test.apikey.apiKey
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function apiKey(connection: IConnection): Promise<apiKey.Output> {
  return PlainFetcher.fetch(connection, {
    ...apiKey.METADATA,
    template: apiKey.METADATA.path,
    path: apiKey.path(),
  });
}
export namespace apiKey {
  export type Output = Primitive<ApiKeyResponseEntity>;

  export const METADATA = {
    method: "GET",
    path: "/test/apikey",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/test/apikey";
}
