import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../../../packages/ui/src/index.css";

import { AlertProvider, ConfirmProvider, NavigationProvider } from "@runa/ui";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <AlertProvider>
          <ConfirmProvider>
            <NavigationProvider>{children}</NavigationProvider>
          </ConfirmProvider>
        </AlertProvider>
      </body>
    </html>
  );
}
