/**
 * @packageDocumentation
 * @module api.functional.test.noauth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { NoAuthResponseEntity } from "../../../../../apps/backend/src/modules/test/entities/test-response.entity";

/**
 * @controller TestController.noAuth
 * @path GET /test/noauth
 * @accessor api.functional.test.noauth.noAuth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function noAuth(connection: IConnection): Promise<noAuth.Output> {
  return PlainFetcher.fetch(connection, {
    ...noAuth.METADATA,
    template: noAuth.METADATA.path,
    path: noAuth.path(),
  });
}
export namespace noAuth {
  export type Output = Primitive<NoAuthResponseEntity>;

  export const METADATA = {
    method: "GET",
    path: "/test/noauth",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/test/noauth";
}
