/**
 * @packageDocumentation
 * @module api.functional.test
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { SessionResponseEntity } from "../../../../apps/backend/src/modules/test/entities/test-response.entity";

export * as noauth from "./noauth/index";
export * as apikey from "./apikey/index";

/**
 * @controller TestController.session
 * @path GET /test/session
 * @accessor api.functional.test.session
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function session(
  connection: IConnection,
): Promise<session.Output> {
  return PlainFetcher.fetch(connection, {
    ...session.METADATA,
    template: session.METADATA.path,
    path: session.path(),
  });
}
export namespace session {
  export type Output = Primitive<SessionResponseEntity>;

  export const METADATA = {
    method: "GET",
    path: "/test/session",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/test/session";
}
