/**
 * @packageDocumentation
 * @module api.functional.tv
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";

import type { SearchTvDto } from "../../../../apps/backend/src/modules/tv/dto/search-tv.dto";
import type { TvSearchEntity } from "../../../../apps/backend/src/modules/tv/entities/tv-search.entity";
import type { TvEntity } from "../../../../apps/backend/src/modules/tv/entities/tv.entity";

/**
 * @controller TvController.search
 * @path GET /tv/search
 * @accessor api.functional.tv.search
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function search(
  connection: IConnection,
  query: search.Query,
): Promise<search.Output> {
  return PlainFetcher.fetch(connection, {
    ...search.METADATA,
    template: search.METADATA.path,
    path: search.path(query),
  });
}
export namespace search {
  export type Query = Resolved<SearchTvDto>;
  export type Output = Primitive<TvSearchEntity>;

  export const METADATA = {
    method: "GET",
    path: "/tv/search",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/tv/search";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}

/**
 * @controller TvController.getTv
 * @path GET /tv/:id
 * @accessor api.functional.tv.getTv
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getTv(
  connection: IConnection,
  id: string,
): Promise<getTv.Output> {
  return PlainFetcher.fetch(connection, {
    ...getTv.METADATA,
    template: getTv.METADATA.path,
    path: getTv.path(id),
  });
}
export namespace getTv {
  export type Output = Primitive<TvEntity>;

  export const METADATA = {
    method: "GET",
    path: "/tv/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/tv/${encodeURIComponent(id?.toString() ?? "null")}`;
}
