/**
 * @packageDocumentation
 * @module api.functional.user
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { User } from "@runa/database";
import type { Primitive } from "typia";

import type { CreateUserDto } from "../../../../apps/backend/src/modules/user/dto/create-user.dto";

/**
 * @controller UserController.create
 * @path POST /user/create
 * @accessor api.functional.user.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  data: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    data,
  );
}
export namespace create {
  export type Body = Primitive<CreateUserDto>;
  export type Output = Primitive<User>;

  export const METADATA = {
    method: "POST",
    path: "/user/create",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/user/create";
}
