/**
 * @packageDocumentation
 * @module api.functional.movie
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";

import type { SearchMovieDto } from "../../../../apps/backend/src/modules/movie/dto/search-movie.dto";
import type { MovieSearchEntity } from "../../../../apps/backend/src/modules/movie/entities/movie-search.entity";
import type { MovieEntity } from "../../../../apps/backend/src/modules/movie/entities/movie.entity";

/**
 * @controller MovieController.search
 * @path GET /movie/search
 * @accessor api.functional.movie.search
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function search(
  connection: IConnection,
  query: search.Query,
): Promise<search.Output> {
  return PlainFetcher.fetch(connection, {
    ...search.METADATA,
    template: search.METADATA.path,
    path: search.path(query),
  });
}
export namespace search {
  export type Query = Resolved<SearchMovieDto>;
  export type Output = Primitive<MovieSearchEntity>;

  export const METADATA = {
    method: "GET",
    path: "/movie/search",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/movie/search";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}

/**
 * @controller MovieController.getMovie
 * @path GET /movie/:id
 * @accessor api.functional.movie.getMovie
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getMovie(
  connection: IConnection,
  id: string,
): Promise<getMovie.Output> {
  return PlainFetcher.fetch(connection, {
    ...getMovie.METADATA,
    template: getMovie.METADATA.path,
    path: getMovie.path(id),
  });
}
export namespace getMovie {
  export type Output = Primitive<MovieEntity>;

  export const METADATA = {
    method: "GET",
    path: "/movie/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/movie/${encodeURIComponent(id?.toString() ?? "null")}`;
}
