/**
 * @packageDocumentation
 * @module api.functional.connection
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { RemoveConnectionDto } from "../../../../apps/backend/src/modules/connection/dto/remove-connection.dto";
import type { UpsertConnectionDto } from "../../../../apps/backend/src/modules/connection/dto/upsert-connection.dto";
import type { ConnectionEntity } from "../../../../apps/backend/src/modules/connection/entities/connection.entity";

/**
 * @controller ConnectionController.findAll
 * @path GET /connection
 * @accessor api.functional.connection.findAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
): Promise<findAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...findAll.METADATA,
    template: findAll.METADATA.path,
    path: findAll.path(),
  });
}
export namespace findAll {
  export type Output = Primitive<Array<ConnectionEntity>>;

  export const METADATA = {
    method: "GET",
    path: "/connection",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/connection";
}

/**
 * @controller ConnectionController.upsert
 * @path POST /connection
 * @accessor api.functional.connection.upsert
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function upsert(
  connection: IConnection,
  body: upsert.Body,
): Promise<upsert.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...upsert.METADATA,
      template: upsert.METADATA.path,
      path: upsert.path(),
    },
    body,
  );
}
export namespace upsert {
  export type Body = Primitive<UpsertConnectionDto>;
  export type Output = Primitive<ConnectionEntity>;

  export const METADATA = {
    method: "POST",
    path: "/connection",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/connection";
}

/**
 * @controller ConnectionController.remove
 * @path DELETE /connection/:provider
 * @accessor api.functional.connection.remove
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function remove(
  connection: IConnection,
  provider: string,
  body: remove.Body,
): Promise<remove.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...remove.METADATA,
      template: remove.METADATA.path,
      path: remove.path(provider),
    },
    body,
  );
}
export namespace remove {
  export type Body = Primitive<RemoveConnectionDto>;
  export type Output = Primitive<{ success: boolean }>;

  export const METADATA = {
    method: "DELETE",
    path: "/connection/:provider",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (provider: string) =>
    `/connection/${encodeURIComponent(provider?.toString() ?? "null")}`;
}
