/**
 * @packageDocumentation
 * @module api.functional.manga
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";

import type { SearchMangaDto } from "../../../../apps/backend/src/modules/manga/dto/search-manga.dto";
import type { MangaSearchEntity } from "../../../../apps/backend/src/modules/manga/entities/manga-search.entity";
import type { MangaEntity } from "../../../../apps/backend/src/modules/manga/entities/manga.entity";

/**
 * @controller MangaController.search
 * @path GET /manga/search
 * @accessor api.functional.manga.search
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function search(
  connection: IConnection,
  query: search.Query,
): Promise<search.Output> {
  return PlainFetcher.fetch(connection, {
    ...search.METADATA,
    template: search.METADATA.path,
    path: search.path(query),
  });
}
export namespace search {
  export type Query = Resolved<SearchMangaDto>;
  export type Output = Primitive<MangaSearchEntity>;

  export const METADATA = {
    method: "GET",
    path: "/manga/search",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/manga/search";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}

/**
 * @controller MangaController.getManga
 * @path GET /manga/:id
 * @accessor api.functional.manga.getManga
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getManga(
  connection: IConnection,
  id: string,
): Promise<getManga.Output> {
  return PlainFetcher.fetch(connection, {
    ...getManga.METADATA,
    template: getManga.METADATA.path,
    path: getManga.path(id),
  });
}
export namespace getManga {
  export type Output = Primitive<MangaEntity>;

  export const METADATA = {
    method: "GET",
    path: "/manga/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/manga/${encodeURIComponent(id?.toString() ?? "null")}`;
}
